# Generated by Django 3.2 on 2021-04-15 16:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('bats', models.BooleanField(choices=[(True, 'Right'), (False, 'Left'), (None, 'Switch')])),
                ('throws', models.BooleanField(choices=[(True, 'Right'), (False, 'Left')])),
                ('height', models.IntegerField(help_text='Centimeter')),
                ('weight', models.IntegerField(help_text='Kilometer')),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
    ]
