# Generated by Django 3.2 on 2021-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bats',
            field=models.CharField(choices=[(True, 'Right'), (False, 'Left'), (None, 'Switch')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='throws',
            field=models.CharField(choices=[(True, 'Right'), (False, 'Left')], max_length=50),
        ),
    ]
