# Generated by Django 3.2 on 2021-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210415_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
        migrations.AlterField(
            model_name='player',
            name='bats',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Switch', 'Switch')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='throws',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], max_length=50),
        ),
    ]
